[package]
name = "memelibre"
version = "0.1.0"
edition = "2021"
default-run = "memelibre"

[dependencies]
axum = "0.8.4"
hyper = { version = "1.6.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio"] }
tera = "1.20.0"
tokio = { version = "1.45.1", features = ["full"] }
tower-http = { version = "0.6.4", features = ["fs"] }
