apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memelibre-tls
  namespace: default
spec:
  secretName: memelibre-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - memelibre.com
    - www.memelibre.com
