apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memelibre-ingress
  namespace: default
  annotations:
    # Rate limiting + Timeout
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    # Security headers
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options DENY;
      add_header X-XSS-Protection "1; mode=block";
    # Others
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "3m"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - memelibre.com
        - www.memelibre.com
      secretName: memelibre-tls-secret
  rules:
    - host: memelibre.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memelibre
                port:
                  number: 80
    - host: www.memelibre.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memelibre
                port:
                  number: 80
